# Generated by Django 4.0.1 on 2022-02-03 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_house_image_alter_house_rent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='house',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
