# Generated by Django 4.0.1 on 2022-02-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_house_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
